### ISSUE TITLE
bug: font link is created with 'subsets' param instead of 'subset'

### ISSUE THREAD

**Issue by Birowsky** [gabiseabra/google-fonts-webpack-plugin#13]
https://github.com/gabiseabra/google-fonts-webpack-plugin/blob/b1700573358651dae47ef379fe9e13cf74dcf25b/src/GoogleWebfonts.js#L90

**Comment by gabiseabra** [comment]
According to google-webfonts-helper docs, the correct query param is "subsets":
https://github.com/majodev/google-webfonts-helper/#get-apifontsidsubsetslatinlatin-ext
Are you having trouble downloading a particular subset with this plugin?

**Comment by Birowsky** [comment]
Sorry, I jumped too quick on coming up with a solution. The actual problem that i'm facing is when the font link is generated, instead of the `subsets` param:
```
<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700&amp;subsets=cyrillic" rel="stylesheet">
```
there should be `subset`:
```
<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700&amp;subset=cyrillic" rel="stylesheet">
```

Just like in Google Fonts:
<img width="779" alt="screen shot 2017-09-20 at 11 50 44" src="https://user-images.githubusercontent.com/3199950/30638033-6ccef890-9dfa-11e7-8ad6-203ef949d846.png">

**Comment by Birowsky** [comment]
🤘
